### ISSUE TITLE
How to connect to mongodb atlass?

### ISSUE THREAD

**Issue by holms** [SouthbankSoftware/dbkoda#28]
MongoDB atlass provides with following link: `mongodb+srv://lympo-io-xxx.mongodb.net/test`

While dbKoda says that mongodb+srv schema is not supported. Well for 3.6 mongo version is totally valid. So what's the problem?

**Comment by gharriso** [comment]
Hi Roman,

You are right we should support this. I've raised a change request and I hope we'll have a nightly build supporting that syntax in a day or two.  

Thanks for trying dbKoda!

Guy Harrison, CTO

**Comment by jaydenseric** [comment]
This issue is closed, but it seems to not be supported yet? At least for v1.0.1.

**Comment by michaeljharrison** [comment]
Hi there!

Sorry this issue was not meant to be closed until we provided a link to a build with the +srv support in it.
We've put up a pre-release version of 1.1 that you can find here:

https://github.com/SouthbankSoftware/dbkoda/releases/tag/1.1rc8

Please note this hasn't been thoroughly tested, so there may be so issues, don't hesitate to let us know if you run into them!

To use the +srv protocol, when creating or editing a profile, in the **Basic Connection** tab, change **Protocol** to `mongodb+srv`.

Hope this helps!

Kind Regards,
Mike from dbKoda.

**Comment by holms** [comment]
@michaeljharrison Just tried 1.1 Beta:

```
2018-08-24T06:54:25+03:00 - error: Window dbKoda: Error: Profile connection failed: Ports not accepted with `mongodb+srv` URIs
    at a (http://localhost:7001/ui/commons.js:1:1865875)
    at convert (http://localhost:7001/ui/commons.js:1:1868417)
    at Emitter.<anonymous> (http://localhost:7001/ui/commons.js:1:7950469)
    at Emitter.onack (http://127.0.0.1:7001/dist/primus.js:3516:11)
    at Emitter.ondata (http://127.0.0.1:7001/dist/primus.js:3430:14)
    at Primus.ondata (http://127.0.0.1:7001/dist/primus.js:3408:17)
    at emitTwo (events.js:125:13)
    at Primus.emit (events.js:213:7)
    at done (http://127.0.0.1:7001/dist/primus.js:2699:48)
    at transform (http://127.0.0.1:7001/dist/primus.js:2670:30) { [Symbol(info)]: undefined }

```

**Comment by holms** [comment]
Alright removed port started to work  :sunny:
